# Generated by Django 3.1.7 on 2021-03-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_buy_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('package_sell_price', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
