# Generated by Django 3.1.7 on 2021-03-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.product'),
        ),
    ]
