# Generated by Django 3.1.7 on 2021-03-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_package_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='amount',
            new_name='package_amount',
        ),
        migrations.AddField(
            model_name='package',
            name='stock_amount',
            field=models.IntegerField(null=True),
        ),
    ]
